---
version: 2
updates:
  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: "weekly"
    assignees: ["brucellino"]
  - package-ecosystem: gomod
    directory: test
    schedule:
      interval: "weekly"
    assignees: ["brucellino"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    assignees: ["brucellino"]
