name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  validate:
    strategy:
      matrix:
        example:
          - simple
    name: validate
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - name: Get latest Consul
        run: |
          release_url=$(curl https://api.releases.hashicorp.com/v1/releases/consul\?limit\=20\&license_class\=oss | jq -r '.[0].builds[] | select (.arch == "amd64" and .os=="linux").url')
          curl -fSL ${release_url} -o consul.zip
          unzip -p consul.zip consul > consul
          chmod u+x consul
      - name: Start Consul dev server
        run: ./consul agent -server -dev &
      - name: Get latest Terraform
        run: |
          release_url=$(curl https://api.releases.hashicorp.com/v1/releases/terraform\?limit\=20\&license_class\=oss | jq -r '. | map(select(.is_prerelease == false)) | .[0].builds[] | select (.arch == "amd64" and .os=="linux").url')
          curl -fSL ${release_url} -o terraform.zip
          unzip -p terraform terraform.zip
          chmod u+x terraform
      - name: Init terraform
        run: ./terraform -chdir=examples/${{ matrix.example }} init
      - name: Validate terraform
        run: ./terraform -chdir=examples/${{ matrix.example }} validate
  Test:
    name: Test
    runs-on: ubuntu-24.04
    needs:
      - validate
    env:
      VAULT_ADDR: "http://localhost:8200"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Consul
        run: |
          curl -fSL https://releases.hashicorp.com/consul/1.15.1/consul_1.15.1_linux_amd64.zip \
          | gunzip -> consul ; chmod u+x consul
      - name: Start Consul dev server
        run: ./consul agent -server -dev &
      - name: Get Vault
        run: |
          curl -fSL https://releases.hashicorp.com/vault/1.13.0/vault_1.13.0_linux_amd64.zip \
          | gunzip -> vault ; chmod u+x vault
      - name: Start Vault dev server
        run: ./vault server -dev -dev-root-token-id=${{ secrets.VAULT_TOKEN }} &
      - name: Add DO mount
        run: ./vault secrets enable -path="digitalocean" -description="KV data" kv-v2
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      - name: Set DO secret
        run: ./vault kv put -mount=digitalocean tokens terraform=${{ secrets.DO_TOKEN }}
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      - name: Get Terraform
        run: |
          curl -fSL https://releases.hashicorp.com/terraform/1.4.2/terraform_1.4.2_linux_amd64.zip \
          | gunzip -> terraform ; chmod u+x terraform
      - name: Test
        run: cd test ; go test


  release:
    needs:
      - validate
      - Test
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: |
          npm install -D '@semantic-release/commit-analyzer' \
          '@semantic-release/release-notes-generator' \
          '@semantic-release/changelog' \
          'semantic-release-license' \
          '@semantic-release/github'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
